[mypy]
# ---------- Básico ----------
python_version = 3.11
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# ---------- Permissividade inicial ----------
# Comece relaxado: não force anotar tudo agora
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
warn_return_any = False
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
strict_optional = True

# ---------- Imports ----------
ignore_missing_imports = True
follow_imports = silent

# ---------- Saída ----------
show_error_codes = True
show_column_numbers = True
pretty = True

# ---------- Exclusões ----------
exclude = (?x)(
    ^build/
    | ^dist/
    | ^\.venv/
    | ^venv/
    | ^node_modules/
    | /migrations/
    | ^docs/
  )

# ---------- Plugin do Django ----------
[mypy.plugins.django-stubs]
django_settings_module = "config.settings.base"

# ---------- Ignorar migrations ----------
[mypy-*.migrations.*]
ignore_errors = True

# ---------- Libs sem stubs (silenciar ruído) ----------
[mypy-environ.*]
ignore_missing_imports = True

[mypy-environ]
ignore_missing_imports = True

# ---------- Arquivos do próprio relatório PEP ----------
# (esses scripts são utilitários, sem necessidade de tipagem estrita)
[mypy-apps.core.management.commands.gerar_relatorio_pep]
ignore_errors = True

[mypy-apps.core.management.commands.gerar_relatorio_pep_all]
ignore_errors = True