[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
disallow_untyped_defs = true

[mypy.plugins.django-stubs]
django_settings_module = config.settings.local
strict_settings = False
strict_model_abstract_attrs = False

[mypy-environ.*]
ignore_missing_imports = True

[mypy-apps.*.migrations.*]
ignore_errors = True

[mypy-apps.core.management.commands.gerar_relatorio_pep]
ignore_errors = True

[mypy-apps.*.tests.*]
disallow_untyped_defs = false

[mypy-apps.*.__tests__.*]
disallow_untyped_defs = false