from .apostila_detalhe import ApostilaAlteracao, ApostilaDetalhe
from .ato_administrativo import AtoAdministrativo
from .cessacao_detalhe import CessacaoDetalhe
from .designacao import ImpedimentoSubstituicao
from .designacao_detalhe import DesignacaoDetalhe
from .insubsistencia_apostila_detalhe import InsubsistenciaApostilaDetalhe
from .insubsistencia_detalhe import InsubsistenciaDetalhe
