# Generated by Django 5.2.16 on 2026-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_cargo",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Código cargo no EOL",
                    ),
                ),
                (
                    "descricao_completa",
                    models.CharField(
                        max_length=255, verbose_name="Descrição completa"
                    ),
                ),
                (
                    "descricao_resumida",
                    models.CharField(
                        max_length=255, verbose_name="Descrição resumida"
                    ),
                ),
                (
                    "grupamento",
                    models.CharField(
                        choices=[
                            ("APOIO_EDUCACAO", "Apoio - educação"),
                            ("DOCENTES", "Docentes"),
                            ("GESTORES_EDUCACAO", "Gestores - educação"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "situacao_funcional",
                    models.CharField(
                        choices=[
                            ("COMISSIONADO", "Cargo em comissão"),
                            ("EFETIVO", "Efetivo"),
                            ("CONTRATADO", "Contratado"),
                        ],
                        max_length=20,
                        verbose_name="Situação funcional",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                            ("EXTINTO", "Extinto"),
                        ],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cargo_base",
                "ordering": ["descricao_resumida"],
            },
        ),
    ]
