# Generated by Django 5.2.16 on 2026-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargobase",
            name="cargo_base_ficticio",
            field=models.BooleanField(
                default=False, verbose_name="Cargo base fictício"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="utilizado_para_designacoes",
            field=models.BooleanField(
                default=True, verbose_name="Utilizado para designações"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="utilizado_para_funcoes",
            field=models.BooleanField(
                default=True, verbose_name="Utilizado para funções"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="utilizado_para_permutas",
            field=models.BooleanField(
                default=False, verbose_name="Utilizado para permutas"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="utilizado_para_ste",
            field=models.BooleanField(
                default=True, verbose_name="Utilizado para STE"
            ),
        ),
    ]
