# Generated by Django 5.2.16 on 2026-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0002_cargobase_cargo_base_ficticio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargobase",
            name="pesquisar_licencas_no_sigpec",
            field=models.BooleanField(
                default=False, verbose_name="Pesquisar Licenças no SIGPEC"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="quantidade_maxima_de_dias_de_licenca",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Quantidade máxima de dias de licença",
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="testar_laudo",
            field=models.BooleanField(
                default=False, verbose_name="Testar laudo"
            ),
        ),
    ]
