# Generated by Django 5.2.16 on 2026-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0003_cargobase_pesquisar_licencas_no_sigpec_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_portaria",
                    models.CharField(
                        choices=[
                            ("DESIGNACAO", "Designação"),
                            ("CESSACAO", "Cessação"),
                            ("APOSTILA", "Apostila"),
                            ("INSUBSISTENCIA", "Insubsistência"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de portaria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("INATIVO", "Inativo")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                (
                    "nome_modelo",
                    models.CharField(
                        max_length=255, verbose_name="Nome do modelo"
                    ),
                ),
                (
                    "tipo_cargo",
                    models.CharField(
                        choices=[
                            ("CARGO_VAGO", "Cargo vago"),
                            ("CARGO_DISPONIVEL", "Cargo disponível"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de cargo",
                    ),
                ),
                (
                    "variaveis",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Variável"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "texto_portaria",
                    models.TextField(verbose_name="Texto da portaria"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "modelo_portaria",
                "ordering": ["nome_modelo"],
            },
        ),
    ]
