# Generated by Django 5.2.16 on 2026-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0004_modeloportaria"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraPortaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao_resumida_cargo",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrição resumida do cargo",
                    ),
                ),
                (
                    "descricao_completa_cargo",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descrição completa do cargo",
                    ),
                ),
                (
                    "codigo_cargo_eol",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Código do cargo no EOL",
                    ),
                ),
                (
                    "tipo_modulo",
                    models.CharField(
                        choices=[
                            (
                                "ESPECIFICO_SUPERVISOR",
                                "Específico - supervisor",
                            ),
                            ("NENHUM", "Nenhum"),
                            ("TURMAS", "Turmas"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de módulo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("INATIVO", "Inativo")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                (
                    "texto_publicacao",
                    models.TextField(
                        verbose_name="Texto para publicação (provimento)"
                    ),
                ),
                (
                    "emitente",
                    models.CharField(
                        choices=[
                            (
                                "SECRETARIO_MUNICIPAL_EDUCACAO",
                                "Secretário municipal de educação",
                            )
                        ],
                        max_length=40,
                    ),
                ),
                ("normas", models.TextField(blank=True, default="")),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "utilizar_numero_sei",
                    models.BooleanField(
                        default=False, verbose_name="Utilizar Nº SEI"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "regra_portaria",
                "ordering": ["descricao_resumida_cargo"],
            },
        ),
    ]
