# Generated by Django 5.2.16 on 2026-08-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_modeloportaria_tipo_ato_pai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloportaria',
            options={'ordering': ['-criado_em']},
        ),
    ]
