# Generated by Django 5.2.16 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0007_populate_cargos_base_designacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargobase",
            name="data_fim_periodo",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Data final do período",
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="permite_substituicao",
            field=models.BooleanField(
                default=False, verbose_name="Permite substituição"
            ),
        ),
        migrations.AddField(
            model_name="cargobase",
            name="possui_periodo_fechado",
            field=models.BooleanField(
                default=False, verbose_name="Possui período fechado"
            ),
        ),
    ]
