# Generated by Django 4.2.27 on 2026-03-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpedimentoSubstituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descricao", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "impedimento_substituicao",
            },
        ),
        migrations.RemoveField(
            model_name="designacao",
            name="impedimento_substituicao",
        ),
        migrations.AddField(
            model_name="designacao",
            name="impedimento_substituicao",
            field=models.ForeignKey(
                to="designacao.impedimentosubstituicao",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="designacoes",
            ),
        ),
    ]
