# Generated by Django 4.2.27 on 2026-04-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designacao', '0004_designacao_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cessacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portaria', models.CharField(max_length=20)),
                ('ano_vigente', models.CharField(max_length=6)),
                ('sei_numero', models.CharField(max_length=30)),
                ('a_pedido', models.BooleanField(default=False)),
                ('remocao', models.BooleanField(default=False)),
                ('aposentadoria', models.BooleanField(default=False)),
                ('data_designacao', models.DateField()),
                ('doc', models.CharField(blank=True, default='', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('designacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cessacao', to='designacao.designacao')),
            ],
            options={
                'db_table': 'cessacao',
            },
        ),
    ]
