# Generated by Django 4.2.27 on 2026-04-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designacao', '0005_cessacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cessacao',
            name='designacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cessacao', to='designacao.designacao'),
        ),
    ]
