# Generated by Django 4.2.27 on 2026-04-16 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0006_alter_cessacao_designacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apostila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APOSTILA", "Apostila"),
                            ("ANULACAO", "Anulação de Apostila"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sei_numero", models.CharField(max_length=30)),
                ("d_o", models.CharField(blank=True, default="", max_length=100)),
                ("observacao", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "apostila_referencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anulacoes",
                        to="designacao.apostila",
                    ),
                ),
                (
                    "cessacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apostilas",
                        to="designacao.cessacao",
                    ),
                ),
                (
                    "designacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apostilas",
                        to="designacao.designacao",
                    ),
                ),
            ],
            options={
                "db_table": "apostila",
            },
        ),
    ]
