# Generated by Django 4.2.28 on 2026-04-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0007_apostila"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insubsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_portaria", models.CharField(max_length=20)),
                ("ano_vigente", models.CharField(max_length=6)),
                ("sei_numero", models.CharField(max_length=30)),
                ("doc", models.CharField(blank=True, default="", max_length=100)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cessacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insubsistencia",
                        to="designacao.cessacao",
                    ),
                ),
                (
                    "designacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insubsistencia",
                        to="designacao.designacao",
                    ),
                ),
            ],
            options={
                "db_table": "insubsistencia",
            },
        ),
    ]
