# Generated by Django 4.2.28 on 2026-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0007_insubsistencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="insubsistencia",
            name="tipo_insubsistencia",
            field=models.CharField(
                choices=[("designacao", "Designacao"), ("cessacao", "Cessacao")],
                default="exit",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
