# Generated by Django 4.2.27 on 2026-05-08 18:19

import django.db.models.deletion
from django.db import migrations, models

ATO_ADMINISTRATIVO = "designacao.atoadministrativo"


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0008_insubsistencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApostilaAlteracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_alterado", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField()),
                ("valor_novo", models.TextField()),
            ],
            options={
                "db_table": "apostila_alteracao",
            },
        ),
        migrations.CreateModel(
            name="AtoAdministrativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DESIGNACAO", "Designação"),
                            ("CESSACAO", "Cessação"),
                            ("APOSTILA", "Apostila"),
                            ("INSUBSISTENCIA", "Insubsistência"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_portaria",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("ano_vigente", models.CharField(blank=True, default="", max_length=6)),
                ("sei_numero", models.CharField(max_length=30)),
                ("doc", models.CharField(blank=True, default="", max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ato_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhos",
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
                (
                    "ato_raiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="descendentes",
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
            ],
            options={
                "db_table": "ato_administrativo",
            },
        ),
        migrations.CreateModel(
            name="ApostilaDetalhe",
            fields=[
                (
                    "ato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="apostila_detalhe",
                        serialize=False,
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
                ("observacao", models.TextField()),
            ],
            options={
                "db_table": "apostila_detalhe",
            },
        ),
        migrations.CreateModel(
            name="CessacaoDetalhe",
            fields=[
                (
                    "ato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cessacao_detalhe",
                        serialize=False,
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
                ("a_pedido", models.BooleanField(default=False)),
                ("remocao", models.BooleanField(default=False)),
                ("aposentadoria", models.BooleanField(default=False)),
                ("data_cessacao", models.DateField()),
            ],
            options={
                "db_table": "cessacao_detalhe",
            },
        ),
        migrations.CreateModel(
            name="DesignacaoDetalhe",
            fields=[
                (
                    "ato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="designacao_detalhe",
                        serialize=False,
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
                ("dre_nome", models.CharField(max_length=255)),
                ("unidade_proponente", models.CharField(max_length=255)),
                ("codigo_hierarquico", models.CharField(max_length=50)),
                ("indicado_nome_civil", models.CharField(max_length=255)),
                ("indicado_nome_servidor", models.CharField(max_length=255)),
                ("indicado_rf", models.CharField(max_length=8)),
                ("indicado_vinculo", models.IntegerField()),
                ("indicado_cargo_base", models.CharField(max_length=255)),
                (
                    "indicado_codigo_cargo_base",
                    models.IntegerField(blank=True, null=True),
                ),
                ("indicado_lotacao", models.CharField(max_length=255)),
                (
                    "indicado_cargo_sobreposto",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "indicado_codigo_cargo_sobreposto",
                    models.IntegerField(blank=True, null=True),
                ),
                ("indicado_local_exercicio", models.CharField(max_length=255)),
                (
                    "indicado_local_servico",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_nome_civil",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_nome_servidor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("titular_rf", models.CharField(blank=True, default="", max_length=8)),
                ("titular_vinculo", models.IntegerField(blank=True, null=True)),
                (
                    "titular_cargo_base",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_codigo_cargo_base",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "titular_lotacao",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_cargo_sobreposto",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_codigo_cargo_sobreposto",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "titular_local_exercicio",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "titular_local_servico",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("carater_excepcional", models.BooleanField(default=False)),
                ("com_afastamento", models.BooleanField(default=False)),
                ("possui_pendencia", models.BooleanField(default=False)),
                ("pendencias", models.TextField(blank=True, default="")),
                ("motivo_afastamento", models.TextField(blank=True, default="")),
                (
                    "tipo_vaga",
                    models.CharField(
                        choices=[
                            ("VAGO", "Cargo Vago"),
                            ("DISPONIVEL", "Cargo Disponível"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cargo_vaga",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (3085, "ASSISTENTE DE DIRETOR DE ESCOLA"),
                            (3360, "DIRETOR DE ESCOLA"),
                            (3379, "COORDENADOR PEDAGOGICO"),
                            (3182, "SECRETARIO DE ESCOLA"),
                            (3352, "SUPERVISOR ESCOLAR"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "impedimento_substituicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designacoes_detalhe",
                        to="designacao.impedimentosubstituicao",
                    ),
                ),
            ],
            options={
                "db_table": "designacao_detalhe",
            },
        ),
        migrations.CreateModel(
            name="InsubsistenciaDetalhe",
            fields=[
                (
                    "ato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="insubsistencia_detalhe",
                        serialize=False,
                        to=ATO_ADMINISTRATIVO,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "insubsistencia_detalhe",
            },
        ),
        migrations.AddField(
            model_name="apostilaalteracao",
            name="apostila",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alteracoes",
                to="designacao.apostiladetalhe",
            ),
        ),
        migrations.AddConstraint(
            model_name="apostilaalteracao",
            constraint=models.UniqueConstraint(
                fields=("apostila", "campo_alterado"), name="unique_campo_por_apostila"
            ),
        ),
    ]
