# Generated by Django 4.2.29 on 2026-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0008_insubsistencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designacao",
            name="indicado_nome_civil",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
