# Generated by Django 4.2.28 on 2026-04-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0008_insubsistencia_tipo_insubsistencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="insubsistencia",
            name="cessacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insubsistencia",
                to="designacao.cessacao",
            ),
        ),
        migrations.AlterField(
            model_name="insubsistencia",
            name="designacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insubsistencia",
                to="designacao.designacao",
            ),
        ),
    ]
