# Generated by Django 4.2.28 on 2026-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0009_alter_designacao_indicado_nome_civil"),
    ]

    operations = [
        migrations.AddField(
            model_name="designacao",
            name="detalhe_para_quadro_de_historico_por_ano",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="designacao",
            name="informacoes_adicionais",
            field=models.TextField(blank=True, default=""),
        ),
    ]
