# Generated by Django 4.2.28 on 2026-04-17 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0007_apostila"),
        ("designacao", "0009_insubsistencia_cessacao_and_more"),
    ]

    operations = []
