# Generated by Django 4.2.28 on 2026-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "designacao",
            "0010_designacao_detalhe_para_quadro_de_historico_por_ano_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="designacao",
            name="dre",
            field=models.CharField(default="109200", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designacao",
            name="ue",
            field=models.CharField(default="013447", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designacao",
            name="funcionarios_da_unidade",
            field=models.CharField(default="3085", max_length=50),
            preserve_default=False,
        ),
    ]
