# Generated by Django 4.2.28 on 2026-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0016_alter_indicado_categoria_max_length_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="atoadministrativo",
            name="status_publicacao",
            field=models.CharField(
                choices=[
                    ("PUBLICADO", "Publicado"),
                    ("NAO_PUBLICADO", "Não Publicado"),
                ],
                default="NAO_PUBLICADO",
                max_length=20,
            ),
        ),
    ]
