# Generated by Django 4.2.30 on 2026-07-06 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("designacao", "0018_insubsistencia_apostila_detalhe"),
    ]

    operations = [
        migrations.AddField(
            model_name="atoadministrativo",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atos_administrativos_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
