# Generated by Django 5.2.16 on 2026-07-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0019_atoadministrativo_criado_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cessacao",
            name="designacao",
        ),
        migrations.RemoveField(
            model_name="insubsistencia",
            name="cessacao",
        ),
        migrations.RemoveField(
            model_name="designacao",
            name="impedimento_substituicao",
        ),
        migrations.RemoveField(
            model_name="insubsistencia",
            name="designacao",
        ),
        migrations.DeleteModel(
            name="Apostila",
        ),
        migrations.DeleteModel(
            name="Cessacao",
        ),
        migrations.DeleteModel(
            name="Designacao",
        ),
        migrations.DeleteModel(
            name="Insubsistencia",
        ),
    ]
