# Generated by Django 5.2.16 on 2026-09-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0022_apostilaalteracao_ato_alterado"),
        ("designacao", "0022_numero_portaria_integer"),
    ]

    operations = []
