# Generated by Django 5.2.16 on 2026-09-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designacao", "0023_merge_20260911_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designacaodetalhe",
            name="cargo_vaga",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
