# Generated by Django 5.2.16 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designacao", "0024_remove_choices_cargo_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="designacaodetalhe",
            name="indicado_codigo_ue_lotacao",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="designacaodetalhe",
            name="indicado_possui_cargo_sobreposto",
            field=models.BooleanField(default=False),
        ),
    ]
